### ISSUE TITLE
0.16.0 command

### ISSUE THREAD

**Issue by Driesboy** [NL-4-DEVS/Pets#13]
command is not working in 0.16.0

**Comment by remotevase** [comment]
What about 1.0?

**Comment by Driesboy** [comment]
?

**Comment by Driesboy** [comment]
im working on a genisys update for 1.0.0.2

Op 10-dec.-2016 15:20 schreef "remote_vase" <notifications@github.com>:

**Comment by remotevase** [comment]
Cool!

**Comment by Driesboy** [comment]
But now i got segmentatiin fault

Op 11-dec.-2016 04:53 schreef "remote_vase" <notifications@github.com>:

Cool!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NL-4-DEVS/Pets/issues/13#issuecomment-266259034>, or mute
the thread

**Comment by Driesboy** [comment]
really ?

**Comment by Driesboy** [comment]
https://github.com/TheBluePinguin1/Genisys/tree/1.0.0

**Comment by Driesboy** [comment]
and what version of php? 7.0.13?

**Comment by Driesboy** [comment]
its after loading 1 plugin and even without plugins

**Comment by Driesboy** [comment]
fixed with 7.0.14

**Comment by Driesboy** [comment]
how to fix this bug?

**Comment by remotevase** [comment]
Idk

**Comment by NemanjaMAX** [comment]
Ik MAYBE
I believe this is syntax error

**Comment by Driesboy** [comment]
its not there is no crash dump
