### ISSUE TITLE
Pets dont spawn

### ISSUE THREAD

**Issue by RyanClarke2** [NL-4-DEVS/Pets#16]
When i try to spawn a cat  or a dog nothing happens and theres no errors on console.The only error i get is from the chicken when i tried to spawn it.
10.05 13:05:42 [Server] INFO Notice: Undefined property: pocketmine\block\Air::$canBeFlowedInto in /plugins/Pets-master/src/pets/entities/Pet.php on line 154
10.05 13:05:42 [Server] Server thread/CRITICAL ClassNotFoundException: "Class pocketmine\network\protocol\AddEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
10.05 13:05:42 [Server] Server thread/CRITICAL Could not tick level "worldd": Class pocketmine\network\protocol\AddEntityPacket not found

**Comment by Driesboy** [comment]
what software are you using

**Comment by RyanClarke2** [comment]
Pocketmine

**Comment by Driesboy** [comment]
PMMP?

**Comment by Driesboy** [comment]
plz use the API3 Brach

**Comment by Driesboy** [comment]
i will create that soon
