### ISSUE TITLE
Add API 3.0.0

### ISSUE THREAD

**Issue by Driesboy** [NL-4-DEVS/Pets#17]

**Comment by teracube** [comment]
Thanks,
and API 6.0.0 or 7.0.0 please ? ;-)))

**Comment by Driesboy** [comment]
:(

Op 20-jul.-2017 17:57 schreef "teracube" <notifications@github.com>:

Thanks,
and API 6.0.0 or 7.0.0 please ? ;-)))

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NL-4-DEVS/Pets/issues/17#issuecomment-316748655>, or mute
the thread
