### ISSUE TITLE
Just A Request :D

### ISSUE THREAD

**Issue by M3fansKingdom2** [NL-4-DEVS/Pets#6]
Hey Developers!
I'm Glad Because Your Pets Plugin Is Awesome :D
I Got A Request For You.
Please Add A Economy On This Pets Plugin.
So I Can Edit The Price Of The Pets.
Thank You,

**Comment by Driesboy** [comment]
for now use advancedkits if you want it and rename the command to make it secret

**Comment by kennethgomad02** [comment]
Could you add a console support and make like /pets <playername> type <type

because it needed to easily use for giving a pets to players using console

**Comment by Driesboy** [comment]
there will be some updates but plz wait
and console support is very difficult

**Comment by kennethgomad02** [comment]
so amm is it possible or now caust it must support so buycraft could sends it

**Comment by Driesboy** [comment]
its not my problem!
i am leaving pocketmine!

**Comment by Driesboy** [comment]
IM BACK

**Comment by Driesboy** [comment]
i will add this soon
i need this in my server soon xD

**Comment by remotevase** [comment]
:+1:

**Comment by Driesboy** [comment]
but now i have exams pray for me

**Comment by remotevase** [comment]
:pray:
